#159206062  Users can search for articles
andela/fargo-ah pull request #30
Opened 2018-08-16 16:53 UTC by klevamane

#### What does this PR do?
- Search for articles by tag, title, and author
#### Description of Task to be completed?
- write units test for the response searching for articles
- return results of searched articles if found

#### How should this be manually tested?
Have the following endpoints working

 GET /api/articles/?tag=tagname

GET /api/articles/?title=title

GET /api/articles/?author=username

 In postman navigate to `http://localhost:3000/api/users`
  
#### Any background context you want to provide?
- Pull in changes and run `npm install`
- Start server with `npm run dev`

#### What are the relevant pivotal tracker stories?
#159206049

[Delivers #159206062]

2018-08-22 20:11 UTC, OKiMaureen approved these changes

2018-08-23 16:08 UTC, Oloyedesinmiloluwa approved these changes

2018-09-06 17:19 UTC, anuonifade commented on helpers/exports.js
> +        [{ firstname: Sequelize.where(Sequelize.col('User.firstname'), { [Op.eq]: `${textToSearch}` }) },
I think it will be better to use `iLike` here as well

2018-09-06 17:20 UTC, anuonifade commented on helpers/exports.js
> +          { lastname: Sequelize.where(Sequelize.col('User.lastname'), { [Op.eq]: `${textToSearch}` }) }
Same here

2018-09-06 17:20 UTC, anuonifade requested changes
Please address my comment

2018-09-06 17:46 UTC, anuonifade approved these changes
LGTM

2018-09-06 17:46 UTC, merged