ch(coveralls): integrate coveralls
andela/fargo-ah pull request #8
Opened 2018-07-26 03:44 UTC by klevamane

#### What does this PR do?
Integrate coveralls code coverage
#### Description of Task to be completed?
- add .coveralls.yml file
- add coveralls badge to readme
#### How should this be manually tested?
- Check the badge in the readme
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/#159232379

2018-07-26 14:40 UTC, andela-aonifade commented on .coveralls.yml
> +repo_token: EttJVT8sAgYCCrcPnC5Cb94xsTHG3oQ7C
Why is this here?

2018-07-26 14:49 UTC, anuonifade requested changes
Please ensure sensitive information is referenced through an environment variable.

2018-07-27 13:53 UTC, andela-aonifade commented on tests/models/initial.test.js
> +});
@klevamane what's up with this? Why is it not fixed?

2018-07-27 14:17 UTC, klevamane commented
The Implementation has already been done.

2018-07-27 14:25 UTC, klevamane commented on tests/models/initial.test.js
> +});
@andela-aonifade I've already fixed it. See the changes below on checks that have passed.

2018-07-27 15:23 UTC, OKiMaureen approved these changes

2018-07-27 15:23 UTC, OKiMaureen commented on .coveralls.yml
> +repo_token: EttJVT8sAgYCCrcPnC5Cb94xsTHG3oQ7C
Good job, However, we can add a newline to the end of the file.

2018-07-27 15:29 UTC, veeqtor commented on app.js
> +import express from 'express';
This app.js file is not needed here, the index.js file is already doing the work.

2018-07-27 15:51 UTC, veeqtor approved these changes

2018-07-27 16:47 UTC, anuonifade approved these changes

2018-07-27 16:47 UTC, merged